// React_Components/src/app/num-bound-components-view/num-bound-components-view.tsx
import { IgrButton, IgrButtonModule, IgrInput, IgrInputModule, IgrRadio, IgrRadioGroup, IgrRadioGroupModule, IgrRadioModule, IgrRating, IgrRatingModule, IgrRipple, IgrRippleModule, IgrSlider, IgrSliderModule } from 'igniteui-react';
import { useNavigate } from 'react-router-dom';
import styles from './num-bound-components-view.module.css';
import createClassTransformer from '../style-utils';

IgrButtonModule.register();
IgrInputModule.register();
IgrRadioGroupModule.register();
IgrRadioModule.register();
IgrRatingModule.register();
IgrRippleModule.register();
IgrSliderModule.register();

export default function NumBoundComponentsView() {
  const navigate = useNavigate();
  const classes = createClassTransformer(styles);
  const numVariable: number = 0;

  return (
    <>
      <div className={classes("row-layout num-bound-components-view-container")}>
        <div className={classes("column-layout group")}>
          <div className={classes("row-layout group_1")}>
            <h4 className={classes("h4")}>
              <span>Component, bound to NUMERIC variable</span>
            </h4>
            <div style={{display: 'contents'}} onClick={() => navigate('/bool-bound-components-view')}>
              <IgrButton variant="Contained" size="large" className={classes("button")}>
                <span>Previous</span>
                <IgrRipple></IgrRipple>
              </IgrButton>
            </div>
            <div style={{display: 'contents'}} onClick={() => navigate('/date-bound-components-view')}>
              <IgrButton variant="Contained" size="large" className={classes("button_1")}>
                <span>Next</span>
                <IgrRipple></IgrRipple>
              </IgrButton>
            </div>
          </div>
          <div className={classes("row-layout group_2")}>
            <div className={classes("column-layout group_3")}>
              <p className={classes("typography__body-1 text")}>
                <span>Value of the variable:</span>
              </p>
              <p className={classes("typography__body-1 text_1")}>
                <span>{numVariable!}</span>
              </p>
            </div>
            <div className={classes("column-layout group_4")}></div>
            <div className={classes("column-layout group_5")}>
              <div className={classes("row-layout group_6")}>
                <p className={classes("typography__body-1 text_2")}>
                  <span>Two way bound components</span>
                </p>
              </div>
              <div className={classes("row-layout group_7")}>
                <div className={classes("column-layout group")}>
                  <div className={classes("column-layout group_8")}>
                    <IgrInput type="number" value="numVariable!" label="Duration" outlined="true" className={classes("input")}></IgrInput>
                  </div>
                  <IgrRating value="numVariable!" size="large" className={classes("rating")}></IgrRating>
                  <IgrRating value="numVariable!" size="large" className={classes("user-input")}></IgrRating>
                  <IgrRadioGroup alignment="horizontal" className={classes("user-input")}>
                    <IgrRadio value="1" className={classes("radio")}>
                      <span>Label</span>
                    </IgrRadio>
                    <IgrRadio value="2" className={classes("radio")}>
                      <span>Label</span>
                    </IgrRadio>
                    <IgrRadio value="3" className={classes("radio")}>
                      <span>Label</span>
                    </IgrRadio>
                  </IgrRadioGroup>
                </div>
                <div className={classes("column-layout group_9")}>
                  <IgrSlider value="numVariable!" min="0" max="100" step="10" discreteTrack="true" className={classes("slider")}></IgrSlider>
                  <IgrSlider value="numVariable!" min="0" max="100" step="10" discreteTrack="true" className={classes("slider")}></IgrSlider>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// Angular_Components/src/app/num-bound-components-view/num-bound-components-view.component.ts
import { Component } from '@angular/core';
import { defineComponents, IgcRatingComponent } from 'igniteui-webcomponents';

defineComponents(IgcRatingComponent);

@Component({
  selector: 'app-num-bound-components-view',
  templateUrl: './num-bound-components-view.component.html',
  styleUrls: ['./num-bound-components-view.component.scss']
})
export class NumBoundComponentsViewComponent {
  public numVariable = 1;
  public numItems = [1, 2, 3];
}

<div class="column-layout group">
  <div class="row-layout group_1">
    <h4 class="h4">
      Component, bound to NUMERIC variable
    </h4>
    <button igxButton="contained" igxRipple routerLink="/bool-bound-components-view" class="button">
      Previous
    </button>
    <button igxButton="contained" igxRipple routerLink="/date-bound-components-view" class="button_1">
      Next
    </button>
  </div>
  <div class="row-layout group_2">
    <div class="column-layout group_3">
      <p class="text">
        Value of the variable:
      </p>
      <p class="text_1">
        {{ numVariable }}
      </p>
    </div>
    <div class="column-layout group_4"></div>
    <div class="column-layout group_5">
      <div class="row-layout group_6">
        <p class="text_2">
          Two way bound components
        </p>
      </div>
      <div class="row-layout group_7">
        <div class="column-layout group">
          <div class="column-layout group_8">
            <igx-input-group type="border" class="input">
              <input type="number" [(ngModel)]="numVariable!" igxInput />
              <label igxLabel>Number input</label>
            </igx-input-group>
          </div>
          <igc-rating [(ngModel)]="numVariable!" size="large" class="rating"></igc-rating>
          <igx-radio-group [(ngModel)]="numVariable" class="radio-group">
            <igx-radio class="radio-sample"
              *ngFor="let item of numItems"
              [value]="item">
                  {{ item }}
            </igx-radio>
          </igx-radio-group>
        </div>
        <div class="column-layout group_9">
          <igx-slider  [primaryTickLabels]="true" [(ngModel)]="numVariable!" [minValue]="0" [maxValue]="5" [step]="1" [showTicks]="true" [secondaryTickLabels]="false"></igx-slider>
        </div>
      </div>
    </div>
  </div>
</div>
