// React_Components/src/app/date-bound-components-view/date-bound-components-view.tsx
import { IgrButton, IgrButtonModule, IgrCalendar, IgrCalendarModule, IgrRipple, IgrRippleModule } from 'igniteui-react';
import { IgrDatePicker, IgrDatePickerModule } from 'igniteui-react-inputs';
import { useNavigate } from 'react-router-dom';
import styles from './date-bound-components-view.module.css';
import createClassTransformer from '../style-utils';

IgrButtonModule.register();
IgrCalendarModule.register();
IgrRippleModule.register();
IgrDatePickerModule.register();

export default function DateBoundComponentsView() {
  const navigate = useNavigate();
  const classes = createClassTransformer(styles);
  const dateVariable: Date = new Date();

  /*
  const StyledDatePicker = ({ className, ...rest }) => (
    <div className={className}>
      <IgrDatePicker {...rest}></IgrDatePicker>
    </div>
  );

  //<StyledDatePicker className={classes("date-picker")} label="Date" value={dateVariable!}></StyledDatePicker>
  */

  return (
    <>
      <div className={classes("row-layout date-bound-components-view-container")}>
        <div className={classes("column-layout group")}>
          <div className={classes("row-layout group_1")}>
            <h4 className={classes("h4")}>
              <span>Component, bound to DATE variable</span>
            </h4>
            <div style={{display: 'contents'}} onClick={() => navigate('/num-bound-components-view')}>
              <IgrButton variant="Contained" size="large" className={classes("button")}>
                <span>Previous</span>
                <IgrRipple></IgrRipple>
              </IgrButton>
            </div>
            <div style={{display: 'contents'}} onClick={() => navigate('/master-view')}>
              <IgrButton variant="Contained" size="large" className={classes("button_1")}>
                <span>Next</span>
                <IgrRipple></IgrRipple>
              </IgrButton>
            </div>
          </div>
          <div className={classes("row-layout group_2")}>
            <div className={classes("column-layout group_3")}>
              <p className={classes("typography__body-1 text")}>
                <span>Value of the variable:</span>
              </p>
              <p className={classes("typography__body-1 text_1")}>
                <span>{dateVariable!.toString()}</span>
              </p>
            </div>
            <div className={classes("column-layout group_4")}></div>
            <div className={classes("column-layout group_5")}>
              <div className={classes("row-layout group_6")}>
                <p className={classes("typography__body-1 text_2")}>
                  <span>Two way bound components</span>
                </p>
              </div>
              <div className={classes("row-layout group_7")}>
                <div className={classes("column-layout group_8")}>
                  <IgrDatePicker label="Date" value={dateVariable!}></IgrDatePicker>
                </div>
                <div className={classes("column-layout group_9")}>
                  <IgrCalendar hideHeader="Horizontal" headerOrientation="horizontal" className={classes("calendar")}></IgrCalendar>
                </div>
                <div className={classes("column-layout group_10")}>
                  <IgrCalendar hideHeader="Horizontal" headerOrientation="horizontal" className={classes("calendar")}></IgrCalendar>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// Angular_Components/src/app/date-bound-components-view/date-bound-components-view.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-date-bound-components-view',
  templateUrl: './date-bound-components-view.component.html',
  styleUrls: ['./date-bound-components-view.component.scss']
})
export class DateBoundComponentsViewComponent {
  public dateVariable?: Date;
}

<div class="column-layout group">
  <div class="row-layout group_1">
    <h4 class="h4">
      Component, bound to DATE variable
    </h4>
    <button igxButton="contained" igxRipple routerLink="/num-bound-components-view" class="button">
      Previous
    </button>
    <button igxButton="contained" igxRipple routerLink="/master-view" class="button_1">
      Next
    </button>
  </div>
  <div class="row-layout group_2">
    <div class="column-layout group_3">
      <p class="text">
        Value of the variable:
      </p>
      <p class="text_1">
        {{ dateVariable }}
      </p>
    </div>
    <div class="column-layout group_4"></div>
    <div class="column-layout group_5">
      <div class="row-layout group_6">
        <p class="text_2">
          Two way bound components
        </p>
      </div>
      <div class="row-layout group_7">
        <div class="column-layout group_8">
          <igx-date-picker [(ngModel)]="dateVariable!" type="border" mode="dialog" class="date-picker">
            <label igxLabel>Date</label>
          </igx-date-picker>
        </div>
        <div class="column-layout group_9">
          <igx-calendar [(ngModel)]="dateVariable!" [hasHeader]="true" [vertical]="false" class="calendar"></igx-calendar>
        </div>
        <div class="column-layout group_10">
          <igx-calendar [(ngModel)]="dateVariable!" [hasHeader]="true" [vertical]="false" class="calendar"></igx-calendar>
        </div>
      </div>
    </div>
  </div>
</div>
