// Date_Picker_And Combo/DPC_WebComponents/src/app/master-view/master-view.ts
import { html, css, LitElement } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { defineComponents, IgcComboComponent, IgcInputComponent } from 'igniteui-webcomponents';
import { CustomersType } from '../models/northwind/customers-type';
import { BoxOfficeRevenueType } from '../models/financial/box-office-revenue-type';
import { financialService } from '../services/Financial-service';
import { northwindService } from '../services/Northwind-service';

defineComponents(IgcComboComponent, IgcInputComponent);

@customElement('app-master-view')
export default class MasterView extends LitElement {
  static styles = css`
    :host {
      height: 100%;
      display: flex;
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
    }
    .date-picker {
      height: max-content;
      min-width: 120px;
      flex-shrink: 0;
    }
    .user-input {
      height: max-content;
      min-width: min-content;
      flex-shrink: 0;
    }
  `;

  constructor() {
    super();
    this.northwindCustomers = northwindService.getData('CustomersType');
    this.financialBoxOfficeRevenue = financialService.getData('BoxOfficeRevenueType');
  }

  @state()
  private dateVar?: Date;

  @state()
  private customerObject?: CustomersType;

  @state()
  private northwindCustomers: CustomersType[] = [];

  @state()
  private financialBoxOfficeRevenue: BoxOfficeRevenueType[] = [];

  public datePickerValueChange(event: any) {
    this.dateVar = new Date(event.TBD);
  }

  public singleSelectComboIgcChange(event: any) {
    this.customerObject = event.detail.newValue[0] as CustomersType;
  }

  render() {
    return html`
      <link rel='stylesheet' href='../../ig-theme.css'>
      <igc-combo ?outlined="${true}" .data="${this.northwindCustomers}" label="Label/Placeholder" display-key="customerID" ?single-select="${true}" @igcChange="${this.singleSelectComboIgcChange}" class="user-input"></igc-combo>
      <igc-input value="${this.customerObject?.customerID}" label="Label/Placeholder" ?outlined="${true}" class="user-input"></igc-input>
    `;
  }
}

// Date_Picker_And Combo/DPC_Angular/src/app/master-view/master-view.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ISimpleComboSelectionChangingEventArgs } from 'igniteui-angular';
import { Subject, takeUntil } from 'rxjs';
import { BoxOfficeRevenueType } from '../models/financial/box-office-revenue-type';
import { CustomersType } from '../models/northwind/customers-type';
import { FinancialService } from '../services/financial.service';
import { NorthwindService } from '../services/northwind.service';

@Component({
  selector: 'app-master-view',
  templateUrl: './master-view.component.html',
  styleUrls: ['./master-view.component.scss']
})
export class MasterViewComponent implements OnInit, OnDestroy {
  private destroy$: Subject<void> = new Subject<void>();
  public dateVar?: Date;
  public customerObject?: CustomersType;
  public northwindCustomers: CustomersType[] = [];
  public financialBoxOfficeRevenue: BoxOfficeRevenueType[] = [];

  constructor(
    private northwindService: NorthwindService,
    private financialService: FinancialService,
  ) {}

  ngOnInit() {
    this.northwindService.getData('CustomersType').pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => this.northwindCustomers = data,
      error: (_err: any) => this.northwindCustomers = []
    });
    this.financialService.getData('BoxOfficeRevenueType').pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => this.financialBoxOfficeRevenue = data,
      error: (_err: any) => this.financialBoxOfficeRevenue = []
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  public datePickerValueChange(event: Date) {
    this.dateVar = new Date(event);
  }

  public singleSelectComboSelectionChanging(event: ISimpleComboSelectionChangingEventArgs) {
    this.customerObject = event.newValue as CustomersType;
  }
}

<!--
<igx-date-picker type="border" mode="dialog" (valueChange)="datePickerValueChange($event)" class="date-picker">
  <label igxLabel>Date</label>
</igx-date-picker>
<igx-simple-combo type="border" [data]="northwindCustomers" displayKey="customerID" (selectionChanging)="singleSelectComboSelectionChanging($event)" class="user-input">
  <label igxLabel>Label/Placeholder</label>
</igx-simple-combo>
<igx-date-picker type="border" mode="dialog" class="date-picker">
  <label igxLabel>Date</label>
</igx-date-picker>
<igx-simple-combo type="border" [data]="financialBoxOfficeRevenue" displayKey="Franchise" class="user-input">
  <label igxLabel>Label/Placeholder</label>
</igx-simple-combo>
<igx-input-group type="border" class="user-input">
  <input type="text" [value]="dateVar!" igxInput />
  <label igxLabel>Label/Placeholder</label>
</igx-input-group>
<igx-input-group type="border" class="user-input">
  <input type="text" [value]="customerObject?.customerID" igxInput />
  <label igxLabel>Label/Placeholder</label>
</igx-input-group>
-->



<!-- DATE PICKER -->
<igx-date-picker type="border" mode="dialog" [(ngModel)]="dateVar" (valueChange)="datePickerValueChange($event)" class="date-picker">
  <label igxLabel>Date</label>
</igx-date-picker>
<igx-input-group type="border" class="user-input">
  <input type="text" [ngModel]="dateVar!" igxInput/>
  <label igxLabel>Label/Placeholder</label>
</igx-input-group>
<!-- 
    if we have just valuechange without ngmodel, its one way binding
    when the value is changed from the first date picker, it doesn't change the value in the second
    but if the value in the second is changed, the first changes as well
  
    if we have both the ngmodel and the valueChange, it works two ways, the same as with jst the ngmodel
-->
<igx-date-picker type="border" mode="dialog" (valueChange)="datePickerValueChange($event)" class="date-picker">
  <label igxLabel>Date</label>
</igx-date-picker>


<!-- COMBO -->
<igx-simple-combo type="border" [data]="northwindCustomers" displayKey="customerID" [(ngModel)]="customerObject" class="user-input">
  <label igxLabel>Label/Placeholder</label>
</igx-simple-combo>
<igx-input-group type="border" class="user-input">
  <input type="text" [value]="customerObject?.customerID" igxInput />
  <label igxLabel>Label/Placeholder</label>
</igx-input-group>
<!-- the same thing like with the date picker -->
<igx-simple-combo type="border" [data]="northwindCustomers" displayKey="customerID" (selectionChanging)="singleSelectComboSelectionChanging($event)" class="user-input">
  <label igxLabel>Label/Placeholder</label>
</igx-simple-combo>
