// React_Components/src/app/master-view/master-view.tsx
import { IgrButton, IgrButtonModule, IgrCombo, IgrComboModule, IgrRipple, IgrRippleModule } from 'igniteui-react';
import { useNavigate } from 'react-router-dom';
import { useGetCategories, useGetCustomers } from '../hooks/northwind-hooks';
import styles from './master-view.module.css';
import createClassTransformer from '../style-utils';
import { CustomersType } from '../models/northwind/customers-type';
import { CategoriesType } from '../models/northwind/categories-type';

IgrButtonModule.register();
IgrComboModule.register();
IgrRippleModule.register();

export default function MasterView() {
  const navigate = useNavigate();
  const classes = createClassTransformer(styles);
  const categoryArray = useGetCategories();
  const customerArray = useGetCustomers();
  const categoryObject: CategoriesType = null;
  const customerOutputArray: CustomersType[] = [];

  return (
    <>
      <div className={classes("row-layout master-view-container")}>
        <div className={classes("column-layout group")}>
          <div className={classes("row-layout group_1")}>
            <h4 className={classes("h4")}>
              <span>Component, bound to OBJECT variable</span>
            </h4>
            <div style={{display: 'contents'}} onClick={() => navigate('/date-bound-components-view')}>
              <IgrButton variant="Contained" size="large" className={classes("button")}>
                <span>Previous</span>
                <IgrRipple></IgrRipple>
              </IgrButton>
            </div>
            <div style={{display: 'contents'}} onClick={() => navigate('/string-bound-components-view')}>
              <IgrButton variant="Contained" size="large" className={classes("button_1")}>
                <span>Next</span>
                <IgrRipple></IgrRipple>
              </IgrButton>
            </div>
          </div>
          <div className={classes("row-layout group_2")}>
            <div className={classes("column-layout group_3")}>
              <p className={classes("typography__body-1 text")}>
                <span>Value of the variable:</span>
              </p>
              <p className={classes("typography__body-1 text_1")}>
                <span>For Simple Combo</span>
              </p>
              <p className={classes("typography__body-1 text_1")}>
                <span>{categoryObject?.name}</span>
              </p>
            </div>
            <div className={classes("column-layout group_4")}></div>
            <div className={classes("column-layout group_5")}>
              <div className={classes("row-layout group_6")}>
                <p className={classes("typography__body-1 text_2")}>
                  <span>Two way bound components</span>
                </p>
              </div>
              <div className={classes("row-layout group_7")}>
                <div className={classes("column-layout group_8")}>
                  <p className={classes("typography__body-1 text_3")}>
                    <span>Simple Combo:</span>
                  </p>
                  <IgrCombo outlined="true" data={categoryArray} label="Label/Placeholder" displayKey="description" singleSelect="true" className={classes("user-input")}></IgrCombo>
                  <IgrCombo outlined="true" data={categoryArray} label="Label/Placeholder" displayKey="description" singleSelect="true" className={classes("user-input_1")}></IgrCombo>
                </div>
                <div className={classes("column-layout group_9")}>
                  <p className={classes("typography__body-1 text_3")}>
                    <span>Combo:</span>
                  </p>
                  <IgrCombo outlined="true" data={customerArray} label="Label/Placeholder" displayKey="customerID" autoFocusSearch="true" disableFiltering="true"  className={classes("user-input")}></IgrCombo>
                  <IgrCombo outlined="true" data={customerArray} label="Label/Placeholder" displayKey="customerID" autoFocusSearch="true" disableFiltering="true" className={classes("user-input_1")}></IgrCombo>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// Angular_Components/src/app/master-view/master-view.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';
import { CustomersType } from '../models/northwind/customers-type';
import { CategoriesType } from '../models/northwind/categories-type';
import { NorthwindService } from '../services/northwind.service';

@Component({
  selector: 'app-master-view',
  templateUrl: './master-view.component.html',
  styleUrls: ['./master-view.component.scss']
})
export class MasterViewComponent implements OnInit, OnDestroy {
  private destroy$: Subject<void> = new Subject<void>();
  public categoryArray: CategoriesType[] = [];
  public categoryObject?: CategoriesType;
  public customerArray: CustomersType[] = [];
  public customerOutputArray: CustomersType[] = [];

  constructor(
    private northwindService: NorthwindService,
  ) {}

  ngOnInit() {
    this.northwindService.getData('CategoriesType').pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => this.categoryArray = data,
      error: (_err: any) => this.categoryArray = []
    });
    this.northwindService.getData('CustomersType').pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => this.customerArray = data,
      error: (_err: any) => this.customerArray = []
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<div class="column-layout group">
  <div class="row-layout group_1">
    <h4 class="h4">
      Component, bound to OBJECT variable
    </h4>
    <button igxButton="contained" igxRipple routerLink="/date-bound-components-view" class="button">
      Previous
    </button>
    <button igxButton="contained" igxRipple routerLink="/string-bound-components-view" class="button_1">
      Next
    </button>
  </div>
  <div class="row-layout group_2">
    <div class="column-layout group_3">
      <p class="text">
        Value of the variable:
      </p>
      <p class="text_1">
        For Simple Combo
      </p>
      <p class="text_1">
        {{ categoryObject?.description }}
      </p>
      <p class="text_2">
        For Combo
      </p>
      <p *ngFor="let item of customerOutputArray" class="text_5">
				{{ item.customerID }}
			</p>
    </div>
    <div class="column-layout group_4"></div>
    <div class="column-layout group_5">
      <div class="row-layout group_6">
        <p class="text_3">
          Two way bound components
        </p>
      </div>
      <div class="row-layout group_7">
        <div class="column-layout group_8">
          <p class="text_4">
            Simple Combo:
          </p>
          <igx-simple-combo type="border" [(ngModel)]="categoryObject!" displayKey="description" [data]="categoryArray" class="user-input">
            <label igxLabel>Label/Placeholder</label>
          </igx-simple-combo>
          <igx-simple-combo type="border" [(ngModel)]="categoryObject!" displayKey="description" [data]="categoryArray" class="user-input_1">
            <label igxLabel>Label/Placeholder</label>
          </igx-simple-combo>
        </div>
        <div class="column-layout group_9">
          <p class="text_4">
            Combo:
          </p>
          <igx-combo type="border" [(ngModel)]="customerOutputArray" displayKey="customerID" [autoFocusSearch]="true" [data]="customerArray" class="user-input">
            <label igxLabel>Label/Placeholder</label>
          </igx-combo>
          <igx-combo type="border" [(ngModel)]="customerOutputArray" displayKey="customerID" [autoFocusSearch]="true" [data]="customerArray" class="user-input_1">
            <label igxLabel>Label/Placeholder</label>
          </igx-combo>
        </div>
      </div>
    </div>
  </div>
</div>
